### ISSUE TITLE
[DUPE] with csgo

### ISSUE THREAD

**Issue by kedavlar** [nulli0n/ExcellentCrates-spigot#56] opened 2022-09-07 13:19 UTC
Some users of my server told me that it is possible to duplicate some things while opening the keys with the CSGO mode .. I know 100% because they had the same glasses and other objects with the lore of that crate that can only be obtained in that way.

At the moment I don't know how they did it, I'm not 100% sure

**Comment by OGreenC** [comment] 2022-09-12 21:56
I'd like to add to this issue, as I think we´re experiencing the same problem on our server.

I´ve provided a video taken by one of my players below (see ~50s)
https://medal.tv/games/minecraft/clips/yZDW2-7s-UJ3T/d1337RAbp9NM?invite=cr-MSxTZ3EsNjY4OTAyOSw

I´ve not been able to reproduce this error, so I originally shook it off as a one-of-a-kind situation, but today I was sent yet another video, of a user getting items from the crate menu (this time only footage from after opening the crate, though)
https://medal.tv/games/minecraft/clips/ADVyjUoeJsw4Y/d1337S51BMt6?invite=cr-MSxtbnEsMTIyNzA5NDIs

I hope the provided video(s) can help shed some light on how / why this is happening.

**Comment by Booquefius** [comment] 2022-09-19 03:15
This has also happened to me with 4.0.5 excellent crates & nex engine 2.2.0 build-18/06/2022

for me it is eating players keys

**Comment by Booquefius** [comment] 2022-09-22 15:49
> > 
> 
> can you pls do a test? use nexengine 2.2.4 and see

it broke the plugin entirely

**Comment by nulli0n** [comment] 2022-12-16 18:39
Should be fixed in the latest plugin version.

**Comment by nulli0n** [comment] 2023-01-06 11:13
Since no one can really reproduce this and due to lack of user feedback, issue will be closed.

**Closed by nulli0n** 2023-01-06 11:13 UTC
